# Generated by Django 5.1.3 on 2024-11-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('Nequi', 'Nequi'), ('Daviplata', 'Daviplata'), ('Efectivo', 'Efectivo'), ('Tarjeta de crédito', 'Tarjeta de crédito'), ('Tarjeta de débito', 'Tarjeta de débito')], max_length=50),
        ),
    ]
